site_name: ReflexSom
site_description: Documentação do projeto de software ReflexSom
site_author: Davi M.

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: black

nav:
  - Início: index.md
  - Documento de visão: 
    - Cenário atual do cliente e do negócio: cenario.md
    - Solução Proposta: solucao.md
    - Estratégias de Engenharia de Software: estrategias.md
    - Engenharia de Requisitos: er.md
    - Cronogramas e Entregas: cronograma.md
    - Interação entre Equipe e Cliente: equipe.md
    - Requisitos de Software: 
      - Lista de requisitos: requisitos.md
      - Priorização e MVP: mvp.md
      - Diagramas: diagramas.md
      - Mapa de Rastreabilidade: mapRast.md
      - Arquitetura: arq.md
    - DoR e DoD: dordod.md
    - Evidências de Execução: evidencias.md
    - Referências Bibliográficas: ref.md
  - Estudos de casos: 
    - Product Backlog Building: pbb.md
    - User Story Mapping: usm.md
  - Lições Aprendidas: licoes.md
  - Apresentações: apresentacoes.md
extra_css:
  - styles.css

